import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import VALogoBar from "./components/VALogoBar";
import { Toaster } from "sonner";
import { AppContextInterface, AppContextProvider } from "./AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appContext: AppContextInterface = { username: "", isLoggedIn: false };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider context={appContext}>
          <header className="relative z-50">
            <VALogoBar />
          </header>
          <main className="flex-1">
            <div>{children}</div>
            <Toaster richColors position="top-right" />
          </main>
        </AppContextProvider>
      </body>
    </html>
  );
}
